
var loaitin = [
{"idLT":"1","Ten":"Thể thao","ThuTu":"1","AnHien":"1","idTL":"1"},
{"idLT":"3","Ten":"Du lịch","ThuTu":"2","AnHien":"1","idTL":"1"},
{"idLT":"4","Ten":"Khoa học","ThuTu":"4","AnHien":"1","idTL":"1"},
{"idLT":"9","Ten":"Xã hội","ThuTu":"3","AnHien":"1","idTL":"1"},
{"idLT":"10","Ten":"Văn hoá","ThuTu":"6","AnHien":"1","idTL":"1"},
{"idLT":"11","Ten":"Pháp luật","ThuTu":"9","AnHien":"1","idTL":"1"},
{"idLT":"12","Ten":"Sống đẹp","ThuTu":"1","AnHien":"1","idTL":"3"},
{"idLT":"24","Ten":"Mẹo vặt","ThuTu":"17","AnHien":"1","idTL":"6"},
{"idLT":"28","Ten":"Thơ hay","ThuTu":"8","AnHien":"1","idTL":"7"},
{"idLT":"40","Ten":"Tools","ThuTu":"10","AnHien":"1","idTL":"9"},
{"idLT":"41","Ten":"Website hữu ích","ThuTu":"11","AnHien":"1","idTL":"9"},
{"idLT":"42","Ten":"Scripts hữu dụng","ThuTu":"12","AnHien":"0","idTL":"9"},
{"idLT":"51","Ten":"Saigon Stories","ThuTu":"20","AnHien":"1","idTL":"18"},
{"idLT":"52","Ten":"People","ThuTu":"21","AnHien":"1","idTL":"18"},
{"idLT":"53","Ten":"Healthcare","ThuTu":"24","AnHien":"0","idTL":"18"},
{"idLT":"54","Ten":"Education","ThuTu":"23","AnHien":"1","idTL":"18"},
{"idLT":"57","Ten":"Traveler's Guide","ThuTu":"34","AnHien":"0","idTL":"11"},
{"idLT":"59","Ten":"Community","ThuTu":"25","AnHien":"1","idTL":"11"},
{"idLT":"61","Ten":"Arts","ThuTu":"30","AnHien":"1","idTL":"11"},
{"idLT":"62","Ten":"Food","ThuTu":"31","AnHien":"1","idTL":"11"},
{"idLT":"64","Ten":"Around the Country","ThuTu":"26","AnHien":"1","idTL":"11"},
{"idLT":"65","Ten":"Movies","ThuTu":"27","AnHien":"0","idTL":"19"},
{"idLT":"66","Ten":"Music","ThuTu":"28","AnHien":"0","idTL":"19"},
{"idLT":"67","Ten":"Exhibitions","ThuTu":"29","AnHien":"1","idTL":"19"},
{"idLT":"69","Ten":"Property News","ThuTu":"32","AnHien":"1","idTL":"15"},
{"idLT":"71","Ten":"Environment","ThuTu":"33","AnHien":"1","idTL":"15"},
{"idLT":"72","Ten":"Financial Markets","ThuTu":"35","AnHien":"1","idTL":"15"},
{"idLT":"73","Ten":"Infrastructure News","ThuTu":"36","AnHien":"1","idTL":"15"},
{"idLT":"74","Ten":"Tourism News","ThuTu":"37","AnHien":"1","idTL":"19"},
{"idLT":"75","Ten":"Động vật","ThuTu":"22","AnHien":"1","idTL":"20"},
{"idLT":"76","Ten":"Sản phẩm mới","ThuTu":"16","AnHien":"1","idTL":"21"},
{"idLT":"77","Ten":"Chia sẻ","ThuTu":"15","AnHien":"1","idTL":"3"},
{"idLT":"78","Ten":"Giáo dục","ThuTu":"18","AnHien":"1","idTL":"1"},
{"idLT":"79","Ten":"Sức khỏe","ThuTu":"7","AnHien":"1","idTL":"6"},
{"idLT":"80","Ten":"Vi tính","ThuTu":"19","AnHien":"1","idTL":"21"},
{"idLT":"81","Ten":"Phong cảnh","ThuTu":"13","AnHien":"0","idTL":"20"},
{"idLT":"82","Ten":"Tin tức web","ThuTu":"14","AnHien":"0","idTL":"9"},
]
