var theloai= [
{"idTL":"1","TenTL":"Tin xã hội","ThuTu":"1","AnHien":"1","lang":"vi"},
{"idTL":"2","TenTL":"Việc làm","ThuTu":"4","AnHien":"0","lang":"vi"},
{"idTL":"3","TenTL":"Nghệ thuật sống","ThuTu":"2","AnHien":"1","lang":"vi"},
{"idTL":"6","TenTL":"Thường thức ","ThuTu":"6","AnHien":"1","lang":"vi"},
{"idTL":"7","TenTL":"Thư giãn","ThuTu":"5","AnHien":"1","lang":"vi"},
{"idTL":"9","TenTL":"Thế giới web","ThuTu":"1","AnHien":"1","lang":"vi"},
{"idTL":"11","TenTL":"Travel","ThuTu":"1","AnHien":"1","lang":"en"},
{"idTL":"12","TenTL":"Health","ThuTu":"5","AnHien":"0","lang":"en"},
{"idTL":"15","TenTL":"Business","ThuTu":"2","AnHien":"1","lang":"en"},
{"idTL":"18","TenTL":"LifeStyle & Living","ThuTu":"3","AnHien":"0","lang":"en"},
{"idTL":"19","TenTL":"Entertainment ","ThuTu":"4","AnHien":"","lang":"en"},
{"idTL":"20","TenTL":"Thiên nhiên","ThuTu":"8","AnHien":"1","lang":"vi"},
{"idTL":"21","TenTL":"Công nghệ","ThuTu":"3","AnHien":"1","lang":"vi"},
{"idTL":"22","TenTL":"MỚI NHẬN","ThuTu":"0","AnHien":"0","lang":"vi"},
{"idTL":"23","TenTL":"HOT","ThuTu":"0","AnHien":"0","lang":"vi"},
]
